# Generated by Django 4.0.3 on 2022-04-09 07:03

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('centralHub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eateries', to='api.centralhub')),
            ],
        ),
    ]
