# Generated by Django 4.0.3 on 2022-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menus', models.ManyToManyField(to='api.menu')),
            ],
        ),
    ]
