# Generated by Django 4.0.3 on 2022-04-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderinvoice_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='api.customer')),
                ('fullMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fullmenu')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mealplan')),
            ],
        ),
    ]
